// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxqlrtuenijjjznmgvpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4cWxydHVlbmlqamp6bm1ndnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzQwMTQsImV4cCI6MjA2NjY1MDAxNH0.KSlqKOF_j34rPszYWDAKsIJP-iDDY0u7VOiUA3L-I-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});